services:
  mariadb:
    image: mariadb:latest
    container_name: secretaria_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: abc123.
      MARIADB_DATABASE: secretaria
      MARIADB_USER: javi
      MARIADB_PASSWORD: abc123.
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: